"""empty message

Revision ID: 0fd1b6b45615
Revises: e2f0417ab556
Create Date: 2024-03-27 13:48:50.032798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd1b6b45615'
down_revision = 'e2f0417ab556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_shutdown', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.drop_column('global_shutdown')

    # ### end Alembic commands ###
