"""empty message

Revision ID: 177f3e943aeb
Revises: b6f640e0327d
Create Date: 2023-11-09 17:05:00.503402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177f3e943aeb'
down_revision = 'b6f640e0327d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_task_id', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.drop_column('notification_task_id')

    # ### end Alembic commands ###
