"""empty message

Revision ID: 32d55721f9ba
Revises: 6192e3aa8b67
Create Date: 2024-01-27 13:07:26.376950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d55721f9ba'
down_revision = '6192e3aa8b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_id', sa.Integer(), nullable=True))
        batch_op.drop_column('cycle_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('ref_id')

    # ### end Alembic commands ###
