"""empty message

Revision ID: 4240e1f23ca2
Revises: 32d55721f9ba
Create Date: 2024-01-27 13:22:17.026745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4240e1f23ca2'
down_revision = '32d55721f9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('notification_task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_task_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
