"""empty message

Revision ID: 501acdb5f0c7
Revises: 7b3227632348
Create Date: 2024-01-17 23:23:17.913269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501acdb5f0c7'
down_revision = '7b3227632348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.Enum('CYCLE_NOTIFICATION', 'SCHEDULE_NOTIFICATION', 'RELEASE_DOOR', 'RECALCULATE_CYCLES_COST', name='taskkinds'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
