"""empty message

Revision ID: 5ecae332bd85
Revises: 0fd1b6b45615
Create Date: 2024-03-29 01:30:57.183245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecae332bd85'
down_revision = '0fd1b6b45615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_scheduling', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.drop_column('require_scheduling')

    # ### end Alembic commands ###
