"""empty message

Revision ID: 7b3227632348
Revises: bbed60bf1361
Create Date: 2024-01-16 22:16:49.263848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3227632348'
down_revision = 'bbed60bf1361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candy_appliance_data', sa.PickleType(), nullable=True))
        batch_op.drop_column('cycle_remaining_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_remaining_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('candy_appliance_data')

    # ### end Alembic commands ###
