"""empty message

Revision ID: 9207493a47b0
Revises: 636ae7396ebc
Create Date: 2023-12-25 16:18:00.390480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9207493a47b0'
down_revision = '636ae7396ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('launch_candy_on_cycle_start', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('launch_candy_on_cycle_start')

    # ### end Alembic commands ###
