"""empty message

Revision ID: 9f55005989a5
Revises: 5fb77350ee50
Create Date: 2023-09-24 22:16:33.960710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f55005989a5'
down_revision = '5fb77350ee50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currentkwh', sa.Numeric(precision=20, scale=4), nullable=True))
        batch_op.drop_column('kwh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kwh', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
        batch_op.drop_column('currentkwh')

    # ### end Alembic commands ###
