"""empty message

Revision ID: b6f640e0327d
Revises: ac2155be2343
Create Date: 2023-10-29 22:18:33.753882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f640e0327d'
down_revision = 'ac2155be2343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_wash_cost', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.drop_column('public_wash_cost')

    # ### end Alembic commands ###
