"""empty message

Revision ID: e2f0417ab556
Revises: 4240e1f23ca2
Create Date: 2024-02-14 20:01:40.529998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f0417ab556'
down_revision = '4240e1f23ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('notification_task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_task_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
