"""empty message

Revision ID: e4d1e906aa58
Revises: 48a0b6007211
Create Date: 2023-09-25 01:06:39.442882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d1e906aa58'
down_revision = '48a0b6007211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('washing_cycles', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
