"""empty message

Revision ID: f23e3609bcda
Revises: 79dd433dcc0c
Create Date: 2024-01-11 00:22:02.967117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23e3609bcda'
down_revision = '79dd433dcc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split_cycles', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split_cycles', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
