"""empty message

Revision ID: fab3523093ca
Revises: f23e3609bcda
Create Date: 2024-01-11 15:04:55.529639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab3523093ca'
down_revision = 'f23e3609bcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split_cycles', schema=None) as batch_op:
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###
